/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FinanceRouteImport } from './routes/_finance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as FinanceIndexRouteImport } from './routes/_finance/index'
import { Route as FinanceAccountsRouteImport } from './routes/_finance/accounts'
import { Route as FinanceCategoriesRouteImport } from './routes/_finance/categories'
import { Route as FinanceExpensesRouteImport } from './routes/_finance/expenses'
import { Route as FinanceIncomeRouteImport } from './routes/_finance/income'
import { Route as FinanceNetWorthRouteImport } from './routes/_finance/net-worth'
import { Route as FinanceStocksRouteImport } from './routes/_finance/stocks'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as ApiInsightsRouteImport } from './routes/api/insights'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const FinanceRoute = FinanceRouteImport.update({
  id: '/_finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAccountsRoute = FinanceAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceCategoriesRoute = FinanceCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceExpensesRoute = FinanceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceIncomeRoute = FinanceIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceNetWorthRoute = FinanceNetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceStocksRoute = FinanceStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => FinanceRoute,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsRoute = ApiInsightsRouteImport.update({
  id: '/api/insights',
  path: '/api/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FinanceIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts': typeof FinanceAccountsRoute
  '/categories': typeof FinanceCategoriesRoute
  '/expenses': typeof FinanceExpensesRoute
  '/income': typeof FinanceIncomeRoute
  '/net-worth': typeof FinanceNetWorthRoute
  '/stocks': typeof FinanceStocksRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts': typeof FinanceAccountsRoute
  '/categories': typeof FinanceCategoriesRoute
  '/expenses': typeof FinanceExpensesRoute
  '/income': typeof FinanceIncomeRoute
  '/net-worth': typeof FinanceNetWorthRoute
  '/stocks': typeof FinanceStocksRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/insights': typeof ApiInsightsRoute
  '/': typeof FinanceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_finance': typeof FinanceRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_finance/accounts': typeof FinanceAccountsRoute
  '/_finance/categories': typeof FinanceCategoriesRoute
  '/_finance/expenses': typeof FinanceExpensesRoute
  '/_finance/income': typeof FinanceIncomeRoute
  '/_finance/net-worth': typeof FinanceNetWorthRoute
  '/_finance/stocks': typeof FinanceStocksRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/insights': typeof ApiInsightsRoute
  '/_finance/': typeof FinanceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/accounts'
    | '/categories'
    | '/expenses'
    | '/income'
    | '/net-worth'
    | '/stocks'
    | '/api/assistant'
    | '/api/insights'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/accounts'
    | '/categories'
    | '/expenses'
    | '/income'
    | '/net-worth'
    | '/stocks'
    | '/api/assistant'
    | '/api/insights'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_finance'
    | '/login'
    | '/register'
    | '/_finance/accounts'
    | '/_finance/categories'
    | '/_finance/expenses'
    | '/_finance/income'
    | '/_finance/net-worth'
    | '/_finance/stocks'
    | '/api/assistant'
    | '/api/insights'
    | '/_finance/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FinanceRoute: typeof FinanceRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  ApiInsightsRoute: typeof ApiInsightsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_finance': {
      id: '/_finance'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_finance/': {
      id: '/_finance/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/_finance/accounts': {
      id: '/_finance/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof FinanceAccountsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/_finance/categories': {
      id: '/_finance/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof FinanceCategoriesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/_finance/expenses': {
      id: '/_finance/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof FinanceExpensesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/_finance/income': {
      id: '/_finance/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof FinanceIncomeRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/_finance/net-worth': {
      id: '/_finance/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof FinanceNetWorthRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/_finance/stocks': {
      id: '/_finance/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof FinanceStocksRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights': {
      id: '/api/insights'
      path: '/api/insights'
      fullPath: '/api/insights'
      preLoaderRoute: typeof ApiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FinanceRouteChildren {
  FinanceAccountsRoute: typeof FinanceAccountsRoute
  FinanceCategoriesRoute: typeof FinanceCategoriesRoute
  FinanceExpensesRoute: typeof FinanceExpensesRoute
  FinanceIncomeRoute: typeof FinanceIncomeRoute
  FinanceNetWorthRoute: typeof FinanceNetWorthRoute
  FinanceStocksRoute: typeof FinanceStocksRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceAccountsRoute: FinanceAccountsRoute,
  FinanceCategoriesRoute: FinanceCategoriesRoute,
  FinanceExpensesRoute: FinanceExpensesRoute,
  FinanceIncomeRoute: FinanceIncomeRoute,
  FinanceNetWorthRoute: FinanceNetWorthRoute,
  FinanceStocksRoute: FinanceStocksRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  FinanceRoute: FinanceRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  ApiInsightsRoute: ApiInsightsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
